### ISSUE TITLE
equipped guns don't work

### ISSUE THREAD

**Issue by zyqunix** [ClassicCounter/launcher#2]
guns that are equipped from the inventory menu do not carry into the actual game. this is rather annoying, since i want to use the usp-s and m4a1-s, as well as the other guns. error also says "Failed to retrieve your items from the server. Please try to access
your Inventory at a later time."

**Comment by heapyxyz** [comment]
What does it have to do with the launcher? 🤔 
If you get `Failed to retrieve your items from the server. Please try to access your Inventory at a later time.` error then your game isn't patched. Make sure to put launcher.exe where csgo.exe is.
